#!/usr/bin/env ruby

STDOUT.sync = true
STDERR.sync = true

require 'rubygems'
require 'bundler'
require 'json'
require 'logger'
Bundler.require

begin
  ALIVE = true

  Signal.trap("TERM") do
    puts "Caught a TERM signal.  Sleeping for 3 seconds and shutting down."
    sleep 3
    exit 3
  end

  class Color < Sinatra::Base
    helpers Sinatra::CustomLogger

    configure do
      $stdout.sync = true
      $stderr.sync = true

      if ENV['LOGFILE']
        log = File.new(ENV['LOGFILE'], "a+")
        $stdout.reopen(log)
        $stderr.reopen(log)
        $stderr.sync = true
        $stdout.sync = true
      end

      set :logger, Logger.new($stdout)
    end

    not_found { "Path #{request.path} is unknown." }

    get '/' do
      return JSON.dump({color: color}) + "\n"
    end

    get '/env' do
      return JSON.pretty_generate(ENV.to_h) + "\n"
    end

    get '/headers' do
      return JSON.pretty_generate(request_headers.to_h) + "\n"
    end

    get '/ping' do
      ping = ::Net::Ping::External.new('8.8.8.8').ping?
      return JSON.dump({can_ping: ping}) + "\n"
    end

    get '/clientip' do
      return "Your IP appears to be #{request.ip}"
    end

    get '/version' do
      return JSON.dump({version: version}) + "\n"
    end

    get '/result' do
      return JSON.dump({color: color, version: version})
    end

    get '/unstable' do
      response = [
        [200, JSON.dump({"luck": "preserved!"})],
        [500, "Explode!"],
      ].sample

      puts "Replying with #{response[0]}: #{response[1]}"
      return response
    end

    get '/error' do
      response = [500, JSON.dump({"error": "not enough magic"})]
      puts "Replying with #{response[0]}: #{response[1]}"
      return response
    end

    get '/exit' do
      puts "Received request for /exit. Terminating."
      File.open("/dev/termination-log", 'w') do |f|
        f.write("Received request for /exit. Terminating.")
      end
      Process.kill('TERM', Process.pid)
      return "Received request for /exit.  Terminating."
    end

    get '/sleep/?:seconds?' do |seconds|
      seconds ||= 10
      puts "Sleeping for #{seconds} seconds."
      sleep(seconds.to_i)
      return JSON.dump({slept: seconds.to_i})
    end

    get '/expensive/?:seconds?' do |seconds|
      seconds = (seconds || 5).to_i
      puts "Doing square roots for #{seconds} seconds..."

      start_time = Time.now
      until Time.now - start_time > seconds
        Math.sqrt(rand(100000))
      end

      return "Did a bunch of work!"
    end

    get '/hang' do
      ::ALIVE = false
      return "Hanging..."
    end

    get '/healthz' do
      return JSON.pretty_generate({"health": "good"}) + "\n"
    end

    private

    def request_headers
      env.select { |k,v| k.start_with? 'HTTP_'}.
        transform_keys { |k| k.sub(/^HTTP_/, '').split('_').map(&:capitalize).join('-') }
    end

    def color
      ENV['COLOR'] || 'UNKNOWN.  Please set the $COLOR environment variable.'
    end

    def version
      ENV["VERSION"] || File.read('VERSION').chomp
    end

  end

  printf "Starting up."
  ENV.fetch('STARTUP_DELAY', 0).to_i.times do |n|
    printf "."
    sleep 1
  end
  puts

  Thread.new do
    begin
      puts "We're alive!"
      while ::ALIVE do
          File.write("/tmp/heartbeat", "alive")
          sleep 1
      end
      puts "We're hung :("
      FileUtils.rm_rf("/tmp/heartbeat")
    rescue Errno::EROFS
      puts "Cannot manage /tmp/heartbeat file in a read-only filesystem."
    end
  end

  Color.run!(show_exceptions: false,
             raise_errors: true,
             traps: false,
             bind: '0.0.0.0',
             port: (ENV["PORT"] || 80))

rescue StandardError => e
  puts e
  File.write("/dev/termination-log", e.to_s)
  exit 2
end
